# specify python as the language
language: python

# python versions to be used for testing
python:
   - "3.5"
 
install:
   - pip install -r requirements.txt

script:
   - cd spec
   - python test_schema.py
   - cd ../src
   - python simple_pattern_tester.py ../spec/test
