# specify python as the language
language: python

# python versions to be used for testing
python:
  - "2.7"

# install jython
before_install:
  - export JYTHON_URL='http://central.maven.org/maven2/org/python/jython-installer/2.7.0/jython-installer-2.7.0.jar'
  - wget $JYTHON_URL -O jython_installer.jar; java -jar jython_installer.jar -s -d $HOME/jython; export PATH=$HOME/jython/bin:$PATH;jython --version

before_script:
  - jython -c "print ''"    # Before run the test case, we need to make jython run some code
  - mvn package             # use maven to assemble java jar dependencies in lib folder
  - export CLASSPATH=lib/*  # set up class using a wildcard (supported as of Java 6 or later)

# test script
script:
    - python src/yaml2json_runner.py patterns/
    - jython -J-Xmx2000m src/abstract_pattern_runner.py patterns/ http://purl.obolibrary.org/obo/go/go-simple.owl 
